// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJHHFTq01fIlo8cDW-4W-N1HfmREduqUM',
    appId: '1:566489030887:web:49a83c5beb18c755cf0242',
    messagingSenderId: '566489030887',
    projectId: 'crud1-5ff73',
    authDomain: 'crud1-5ff73.firebaseapp.com',
    storageBucket: 'crud1-5ff73.appspot.com',
    measurementId: 'G-5WWTZR1R3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgs3g4XCNAAYjKQ-ESIJLEd92xxs6XWaE',
    appId: '1:566489030887:android:a03f239ba643ce6dcf0242',
    messagingSenderId: '566489030887',
    projectId: 'crud1-5ff73',
    storageBucket: 'crud1-5ff73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0FevsVLLytlSJpWv_W5C35v1gl2he8kE',
    appId: '1:566489030887:ios:29e057dcfd378e49cf0242',
    messagingSenderId: '566489030887',
    projectId: 'crud1-5ff73',
    storageBucket: 'crud1-5ff73.appspot.com',
    iosBundleId: 'com.example.crud1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0FevsVLLytlSJpWv_W5C35v1gl2he8kE',
    appId: '1:566489030887:ios:29e057dcfd378e49cf0242',
    messagingSenderId: '566489030887',
    projectId: 'crud1-5ff73',
    storageBucket: 'crud1-5ff73.appspot.com',
    iosBundleId: 'com.example.crud1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJHHFTq01fIlo8cDW-4W-N1HfmREduqUM',
    appId: '1:566489030887:web:005f235f017e157fcf0242',
    messagingSenderId: '566489030887',
    projectId: 'crud1-5ff73',
    authDomain: 'crud1-5ff73.firebaseapp.com',
    storageBucket: 'crud1-5ff73.appspot.com',
    measurementId: 'G-9NHRY3SHGF',
  );
}
